name: ASP.NET Core CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    
    - name: Restore
      run: dotnet restore
    
    - name: Build with dotnet
      run: dotnet build --configuration Release


    - name: Dotnet Publish
      run: dotnet publish --configuration Release -o netcore 
      
  automerge:
     name: Merge Pull Request
     runs-on: [ubuntu-latest]
     needs: [build]
     if: github.base_ref == 'master'
     steps:
       - name: Merge
         uses: actions/github-script@0.2.0
         with:
           script: |
             github.pullRequests.merge({
               owner: context.payload.repository.owner.login,
               repo: context.payload.repository.name,
               pull_number: context.payload.pull_request.number
             })
           github-token: ${{github.token}}
      


